-- =====================================================================
-- 00000000000000_baseline_pre_migrations.sql
--
-- RECONSTRUCTED FROM LIVE PRODUCTION on 2026-08-15 (D-40).
-- Generated by reading pg_catalog / information_schema through the
-- Supabase MCP connector. Production was READ ONLY: no migration repair,
-- no db push, no db pull, no write to supabase_migrations.schema_migrations.
--
-- WHY THIS FILE EXISTS
--   The supabase/migrations directory has never been this database's
--   origin. 38 migration files create 37 tables; production has 67.
--   31 of them -- including public.athlete, which the FIRST migration
--   FK-references on its THIRD line -- have no creating migration at all.
--   A clean database therefore could not replay the history: it stopped at
--   20260709_multi_sport_junctions.sql with "relation public.athlete does
--   not exist". This file supplies exactly the objects the migrations
--   assume already exist, so baseline + the 38 historical migrations can
--   rebuild the schema from empty.
--
-- WHAT IS IN HERE
--   Only objects NO migration creates: the athlytica_core schema, 2
--   extensions, 16 enum types, 31 tables with columns/defaults/constraints/
--   indexes, 5 functions, 3 triggers, 3 views, RLS enablement, client grants.
--
-- WHAT IS DELIBERATELY NOT IN HERE
--   * RLS POLICIES. Every policy on these tables is created by
--     20260720100000_sec001_full_surface_rls_lockdown.sql, which uses
--     "drop policy if exists" before each "create policy". Duplicating them
--     here would give one object two owners.
--   * Anything the 38 migrations create. No migration was reordered,
--     rewritten or deleted.
--   * Data. Schema only. No athlete, guardian, payment or registration row.
--
-- REPLAY SAFETY
--   Three later migrations touch tables defined here, and all three are
--   idempotent, so baseline-then-migrations replays cleanly:
--     20260714_sync_monitoring.sql      ALTER TABLE athlete ADD COLUMN IF NOT EXISTS passport_id
--                                       CREATE UNIQUE INDEX IF NOT EXISTS uq_athlete_passport_id
--     20260812090000_bigice_catalog...  add column if not exists (x9, commercial_price_tier)
--     20260720100000_sec001...          drop policy if exists / create policy (metric_value)
--
--   LIMITATION, STATED RATHER THAN HIDDEN: the columns those migrations add
--   are ALREADY PRESENT below, because this is a snapshot of the CURRENT
--   schema, not of a pre-migration state that no longer exists anywhere.
--   Replaying baseline + migrations reproduces TODAY's schema, not the
--   schema as it stood on 2026-07-09. The name "pre_migrations" describes
--   its POSITION in the chain, not the date of its contents.
--
-- DO NOT REPLAY AGAINST PRODUCTION. Every statement is IF NOT EXISTS or
-- otherwise idempotent, so it should be inert there -- but this file exists
-- for local reconstruction, and production already holds every object in it.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. SCHEMA AND EXTENSIONS
-- ---------------------------------------------------------------------

create schema if not exists athlytica_core;

create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists "pgcrypto"  with schema extensions;


-- ---------------------------------------------------------------------
-- 2. ENUM TYPES (16) -- no migration contains a CREATE TYPE
-- ---------------------------------------------------------------------

do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='verification_status' and n.nspname='public') then create type public.verification_status as enum ('unverified', 'pending', 'verified', 'disputed', 'revoked'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='data_source_type' and n.nspname='public') then create type public.data_source_type as enum ('self_reported', 'club_official', 'federation_official', 'independent_clinic', 'agent_submission', 'witness_attestation', 'video_verified', 'insurer_medical_exam', 'government_id_registry'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='verification_method_type' and n.nspname='public') then create type public.verification_method_type as enum ('document_check', 'biometric_lab_cross_reference', 'witness_corroboration', 'federation_registry_match', 'hash_anchor_confirmation', 'government_id_check', 'none'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='actor_role_type' and n.nspname='public') then create type public.actor_role_type as enum ('club_admin', 'federation_admin', 'agent', 'clinician', 'athlete', 'guardian', 'athlytica_ops', 'insurer_underwriter'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='registration_type_enum' and n.nspname='public') then create type public.registration_type_enum as enum ('first_registration', 'amateur', 'professional', 'loan', 'transfer_permanent', 'transfer_temporary'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='age_band_enum' and n.nspname='public') then create type public.age_band_enum as enum ('under_12_ineligible', '12_15', '16_23', 'over_23_ineligible'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='injury_severity_enum' and n.nspname='public') then create type public.injury_severity_enum as enum ('minor', 'moderate', 'severe', 'career_threatening'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='claim_type_enum' and n.nspname='public') then create type public.claim_type_enum as enum ('first_contact', 'representation_agreement', 'negotiation_mandate', 'termination'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='dispute_status_enum' and n.nspname='public') then create type public.dispute_status_enum as enum ('none', 'contested', 'resolved_upheld', 'resolved_overturned'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='bone_age_method_enum' and n.nspname='public') then create type public.bone_age_method_enum as enum ('greulich_pyle', 'tw3', 'tw2', 'other'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='commercial_asset_category_enum' and n.nspname='public') then create type public.commercial_asset_category_enum as enum ('skate', 'junior_armor_kit', 'composite_stick'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='commercial_product_line_enum' and n.nspname='public') then create type public.commercial_product_line_enum as enum ('hf1_skate', 'v8_junior_armor_kit', 'w1_composite_stick'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='digital_product_type_enum' and n.nspname='public') then create type public.digital_product_type_enum as enum ('skating_masterclass_media', 'education_course_pdf'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='training_track_type_enum' and n.nspname='public') then create type public.training_track_type_enum as enum ('basic_skating', 'figure_skating_precision'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='cohort_enrollment_status_enum' and n.nspname='public') then create type public.cohort_enrollment_status_enum as enum ('enrolled', 'waitlisted', 'cancelled', 'completed'); end if; end $$;
do $$ begin if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace where t.typname='commercial_tier_group_enum' and n.nspname='public') then create type public.commercial_tier_group_enum as enum ('intake_funnel', 'academy'); end if; end $$;


-- ---------------------------------------------------------------------
-- 3. TABLES (31) -- columns only. Foreign keys are added in section 4 so
--    creation order does not matter.
-- ---------------------------------------------------------------------

create table if not exists athlytica_core.athletes (
  athlete_id uuid default gen_random_uuid() not null,
  ath_code character varying(12),
  full_name character varying(100) not null,
  birth_certificate_hash character varying(64) not null,
  profile_photo_url text,
  parent_id uuid,
  created_at timestamp with time zone default CURRENT_TIMESTAMP
);

create table if not exists athlytica_core.parents (
  parent_id uuid default gen_random_uuid() not null,
  phone_number character varying(20) not null,
  is_verified boolean default false,
  created_at timestamp with time zone default CURRENT_TIMESTAMP
);

create table if not exists athlytica_core.performance_logs (
  log_id uuid default gen_random_uuid() not null,
  athlete_id uuid,
  taxonomy_node character varying(50) not null,
  metrics jsonb not null,
  video_url text,
  video_thumbnail text,
  video_duration integer,
  venue_trust_layer boolean default false,
  verification_status character varying(20) default 'PENDING'::character varying,
  recorded_at timestamp with time zone not null,
  verified_by uuid
);

create table if not exists athlytica_core.scalable_id_sequence (
  id integer default 1 not null,
  current_value integer default 500
);

create table if not exists public.agency (
  agency_id uuid default gen_random_uuid() not null,
  name text not null,
  fifa_licence_ref text
);

create table if not exists public.agent (
  agent_id uuid default gen_random_uuid() not null,
  agency_id uuid,
  legal_name text not null,
  fifa_licence_ref text
);

create table if not exists public.athlete (
  athlete_id uuid default gen_random_uuid() not null,
  legal_name text not null,
  preferred_name text,
  date_of_birth date not null,
  sex_at_birth text,
  nationalities character(3)[] default '{}'::bpchar[],
  national_id_hash character(64),
  current_status text default 'active'::text not null,
  primary_sport_code text not null,
  provenance_id uuid not null,
  created_at timestamp with time zone default now() not null,
  passport_id text,
  is_dob_estimated boolean default false,
  is_legacy boolean default true,
  claim_token character varying,
  parent_email character varying
);

create table if not exists public.audit_log (
  event_id uuid default gen_random_uuid() not null,
  event_type text not null,
  actor_id uuid not null,
  occurred_at timestamp with time zone default now() not null,
  record_type text not null,
  record_id uuid not null,
  prev_event_hash character(64),
  event_hash character(64) not null,
  payload_snapshot jsonb
);

create table if not exists public.biometric_record (
  record_id uuid default gen_random_uuid() not null,
  athlete_id uuid not null,
  measured_at date not null,
  age_at_measurement_years numeric(4,2) not null,
  height_cm numeric(5,2),
  weight_kg numeric(5,2),
  bone_age_estimate_years numeric(4,2),
  bone_age_method bone_age_method_enum,
  -- GENERATED, not a default: pg_attrdef reports the expression for both,
  -- and reading it as a default fails with 0A000 "cannot use column
  -- reference in DEFAULT expression". Caught by the local replay, which is
  -- the only check that would have caught it. attgenerated = 's' (STORED).
  chronological_bone_age_delta numeric(4,2) generated always as (age_at_measurement_years - bone_age_estimate_years) stored,
  tanner_stage smallint,
  measurement_method text not null,
  examiner_id uuid,
  provenance_id uuid not null
);

create table if not exists public.club (
  club_id uuid default gen_random_uuid() not null,
  name text not null,
  federation_id uuid,
  country_code character(3),
  is_training_club boolean default false not null
);

create table if not exists public.cohort_session_registry (
  registry_id uuid default gen_random_uuid() not null,
  track_type training_track_type_enum not null,
  cohort_label text not null,
  session_slot integer not null,
  session_day_of_week smallint,
  window_start_time time without time zone not null,
  window_end_time time without time zone not null,
  capacity integer not null,
  season_start_date date not null,
  season_end_date date not null,
  student_athlete_id uuid not null,
  price_tier_id uuid,
  enrollment_status cohort_enrollment_status_enum default 'enrolled'::cohort_enrollment_status_enum not null,
  enrolled_at timestamp with time zone default now() not null
);

create table if not exists public.commercial_inventory (
  inventory_id uuid default gen_random_uuid() not null,
  sku text not null,
  product_line commercial_product_line_enum not null,
  asset_category commercial_asset_category_enum not null,
  product_name text not null,
  size_spec text,
  factory_origin_country character(3),
  import_batch_ref text,
  unit_cost numeric(10,2) not null,
  unit_price numeric(10,2) not null,
  quantity_on_hand integer default 0 not null,
  reorder_threshold integer default 0 not null,
  issued_to_athlete_id uuid,
  is_active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.commercial_price_tier (
  tier_id uuid default gen_random_uuid() not null,
  tier_name text not null,
  tier_group commercial_tier_group_enum not null,
  price_amount numeric(12,2) not null,
  currency character(3) default 'KES'::bpchar not null,
  is_active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  description text,
  best_for text,
  age_range text,
  duration_label text,
  session_format text,
  sessions_included text,
  location text,
  inclusions text[] default '{}'::text[] not null,
  display_order integer default 0 not null,
  is_featured boolean default false not null
);

create table if not exists public.competition_event (
  competition_event_id uuid default gen_random_uuid() not null,
  name text not null,
  competition_level text,
  sport_code text not null,
  event_date date not null,
  location_country_code character(3)
);

create table if not exists public.custody_record (
  custody_id uuid default gen_random_uuid() not null,
  athlete_id uuid not null,
  club_id uuid not null,
  federation_id uuid,
  registration_type registration_type_enum not null,
  start_date date not null,
  end_date date,
  age_at_start_years numeric(4,2),
  age_band age_band_enum,
  is_training_club_flag boolean default false not null,
  transfer_id uuid,
  provenance_id uuid not null
);

create table if not exists public.digital_product_ledger (
  ledger_id uuid default gen_random_uuid() not null,
  product_type digital_product_type_enum not null,
  title text not null,
  file_path text not null,
  verification_token_encrypted text not null,
  token_expires_at timestamp with time zone,
  document_size_bytes bigint not null,
  checksum_sha256 character(64),
  licensed_to_athlete_id uuid not null,
  is_active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.discipline_taxonomy (
  discipline_code text not null,
  sport_code text not null,
  display_name text not null
);

create table if not exists public.division (
  division_id uuid default gen_random_uuid() not null,
  division_code text not null,
  name text not null,
  sport_code text not null,
  age_min_years numeric(4,2) not null,
  age_max_years numeric(4,2) not null,
  co_ed boolean default true not null,
  provenance_id uuid not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.division_scoring_rule (
  rule_id uuid default gen_random_uuid() not null,
  division_id uuid not null,
  sport_code text not null,
  rule_type text not null,
  rule_key text not null,
  threshold_min_seconds numeric(4,2),
  threshold_max_seconds numeric(4,2),
  points jsonb not null,
  provenance_id uuid not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.federation (
  federation_id uuid default gen_random_uuid() not null,
  name text not null,
  country_code character(3),
  sport_code text
);

create table if not exists public.google_form_submission_log (
  submission_id text not null,
  athlete_id uuid not null,
  registry_id uuid not null,
  received_at timestamp with time zone default now() not null
);

create table if not exists public.guardian_contact (
  guardian_id uuid default gen_random_uuid() not null,
  athlete_id uuid not null,
  legal_name text not null,
  relationship text not null,
  contact_info text,
  consent_on_file boolean default false not null,
  consent_date date
);

create table if not exists public.injury_record (
  injury_record_id uuid default gen_random_uuid() not null,
  athlete_id uuid not null,
  injury_date date not null,
  injury_type text,
  icd10_code text,
  body_region text,
  severity injury_severity_enum not null,
  mechanism text,
  days_lost integer,
  return_to_play_date date,
  recurrence_flag boolean default false not null,
  treating_clinician_id uuid,
  training_hours_last_4wk numeric(5,2),
  match_count_last_90d integer,
  provenance_id uuid not null
);

create table if not exists public.metric_registry (
  metric_code text not null,
  sport_code text not null,
  discipline_code text,
  display_name text not null,
  unit text not null,
  data_type text default 'numeric'::text not null,
  is_active boolean default true not null,
  registered_at timestamp with time zone default now() not null
);

create table if not exists public.metric_value (
  metric_value_id uuid default gen_random_uuid() not null,
  sport_profile_id uuid,
  performance_record_id uuid,
  metric_code text not null,
  value_numeric numeric,
  value_text text,
  value_boolean boolean,
  measured_at timestamp with time zone not null,
  context text,
  provenance_id uuid not null
);

create table if not exists public.performance_record (
  performance_record_id uuid default gen_random_uuid() not null,
  athlete_id uuid not null,
  competition_event_id uuid,
  sport_code text not null,
  discipline_code text,
  placement integer,
  video_evidence_hash character(64),
  provenance_id uuid not null
);

create table if not exists public.provenance (
  provenance_id uuid default gen_random_uuid() not null,
  data_source data_source_type not null,
  entered_by_actor_id uuid not null,
  entered_by_actor_role actor_role_type not null,
  entered_at timestamp with time zone default now() not null,
  verified_by_actor_id uuid,
  verified_by_org text,
  verified_at timestamp with time zone,
  verification_method verification_method_type default 'none'::verification_method_type not null,
  verification_status verification_status default 'unverified'::verification_status not null,
  confidence_score numeric(3,2),
  source_document_hash character(64),
  witness_ids uuid[] default '{}'::uuid[]
);

create table if not exists public.representation_claim (
  claim_id uuid default gen_random_uuid() not null,
  athlete_id uuid not null,
  agent_id uuid not null,
  agency_id uuid,
  claim_type claim_type_enum not null,
  claimed_at timestamp with time zone default now() not null,
  effective_from date,
  effective_to date,
  contract_reference_hash character(64),
  dispute_status dispute_status_enum default 'none'::dispute_status_enum not null,
  provenance_id uuid not null
);

create table if not exists public.sport_profile (
  sport_profile_id uuid default gen_random_uuid() not null,
  athlete_id uuid not null,
  sport_code text not null,
  discipline_code text,
  role_position text,
  dominant_side text,
  provenance_id uuid not null
);

create table if not exists public.sport_taxonomy (
  sport_code text not null,
  display_name text not null,
  is_active boolean default true not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.transfer_event (
  transfer_id uuid default gen_random_uuid() not null,
  athlete_id uuid not null,
  transfer_date date not null,
  transfer_fee_amount numeric(14,2),
  transfer_fee_currency character(3) default 'USD'::bpchar,
  transferring_club_id uuid,
  receiving_club_id uuid,
  provenance_id uuid not null
);


-- ---------------------------------------------------------------------
-- 4. CONSTRAINTS -- primary keys, uniques, checks, then foreign keys.
--    Wrapped so the file stays replayable: a constraint that already
--    exists is skipped rather than aborting the run.
-- ---------------------------------------------------------------------

do $$
declare stmt text;
begin
  foreach stmt in array array[
    'alter table athlytica_core.athletes add constraint athletes_pkey PRIMARY KEY (athlete_id)',
    'alter table athlytica_core.athletes add constraint athletes_ath_code_key UNIQUE (ath_code)',
    'alter table athlytica_core.athletes add constraint athletes_birth_certificate_hash_key UNIQUE (birth_certificate_hash)',
    'alter table athlytica_core.parents add constraint parents_pkey PRIMARY KEY (parent_id)',
    'alter table athlytica_core.parents add constraint parents_phone_number_key UNIQUE (phone_number)',
    'alter table athlytica_core.performance_logs add constraint performance_logs_pkey PRIMARY KEY (log_id)',
    'alter table athlytica_core.scalable_id_sequence add constraint scalable_id_sequence_pkey PRIMARY KEY (id)',
    'alter table public.agency add constraint agency_pkey PRIMARY KEY (agency_id)',
    'alter table public.agent add constraint agent_pkey PRIMARY KEY (agent_id)',
    'alter table public.athlete add constraint athlete_pkey PRIMARY KEY (athlete_id)',
    'alter table public.athlete add constraint athlete_claim_token_key UNIQUE (claim_token)',
    'alter table public.athlete add constraint athlete_passport_id_key UNIQUE (passport_id)',
    'alter table public.athlete add constraint athlete_current_status_check CHECK ((current_status = ANY (ARRAY[''active''::text, ''inactive''::text, ''retired''::text, ''suspended''::text, ''deceased''::text])))',
    'alter table public.athlete add constraint athlete_sex_at_birth_check CHECK ((sex_at_birth = ANY (ARRAY[''male''::text, ''female''::text, ''intersex''::text, ''undisclosed''::text])))',
    'alter table public.audit_log add constraint audit_log_pkey PRIMARY KEY (event_id)',
    'alter table public.audit_log add constraint audit_log_event_type_check CHECK ((event_type = ANY (ARRAY[''record_created''::text, ''record_updated''::text, ''record_verified''::text, ''record_disputed''::text, ''record_revoked''::text])))',
    'alter table public.biometric_record add constraint biometric_record_pkey PRIMARY KEY (record_id)',
    'alter table public.biometric_record add constraint biometric_record_measurement_method_check CHECK ((measurement_method = ANY (ARRAY[''self_reported''::text, ''club_medical_staff''::text, ''independent_clinic''::text, ''federation_medical_panel''::text])))',
    'alter table public.biometric_record add constraint biometric_record_tanner_stage_check CHECK (((tanner_stage >= 1) AND (tanner_stage <= 5)))',
    'alter table public.club add constraint club_pkey PRIMARY KEY (club_id)',
    'alter table public.cohort_session_registry add constraint cohort_session_registry_pkey PRIMARY KEY (registry_id)',
    'alter table public.cohort_session_registry add constraint cohort_session_registry_track_type_session_slot_student_ath_key UNIQUE (track_type, session_slot, student_athlete_id, season_start_date)',
    'alter table public.cohort_session_registry add constraint cohort_session_registry_capacity_check CHECK ((capacity > 0))',
    'alter table public.cohort_session_registry add constraint cohort_session_registry_check CHECK ((window_end_time > window_start_time))',
    'alter table public.cohort_session_registry add constraint cohort_session_registry_check1 CHECK ((season_end_date >= season_start_date))',
    'alter table public.cohort_session_registry add constraint cohort_session_registry_session_day_of_week_check CHECK (((session_day_of_week >= 0) AND (session_day_of_week <= 6)))',
    'alter table public.cohort_session_registry add constraint cohort_session_registry_session_slot_check CHECK ((session_slot > 0))',
    'alter table public.commercial_inventory add constraint commercial_inventory_pkey PRIMARY KEY (inventory_id)',
    'alter table public.commercial_inventory add constraint commercial_inventory_sku_key UNIQUE (sku)',
    'alter table public.commercial_inventory add constraint commercial_inventory_quantity_on_hand_check CHECK ((quantity_on_hand >= 0))',
    'alter table public.commercial_inventory add constraint commercial_inventory_reorder_threshold_check CHECK ((reorder_threshold >= 0))',
    'alter table public.commercial_inventory add constraint commercial_inventory_unit_cost_check CHECK ((unit_cost >= (0)::numeric))',
    'alter table public.commercial_inventory add constraint commercial_inventory_unit_price_check CHECK ((unit_price >= (0)::numeric))',
    'alter table public.commercial_price_tier add constraint commercial_price_tier_pkey PRIMARY KEY (tier_id)',
    'alter table public.commercial_price_tier add constraint commercial_price_tier_tier_name_key UNIQUE (tier_name)',
    'alter table public.commercial_price_tier add constraint commercial_price_tier_price_amount_check CHECK ((price_amount >= (0)::numeric))',
    'alter table public.competition_event add constraint competition_event_pkey PRIMARY KEY (competition_event_id)',
    'alter table public.competition_event add constraint competition_event_competition_level_check CHECK ((competition_level = ANY (ARRAY[''club''::text, ''regional''::text, ''national''::text, ''continental''::text, ''international''::text])))',
    'alter table public.custody_record add constraint custody_record_pkey PRIMARY KEY (custody_id)',
    'alter table public.custody_record add constraint custody_record_check CHECK (((end_date IS NULL) OR (end_date >= start_date)))',
    'alter table public.digital_product_ledger add constraint digital_product_ledger_pkey PRIMARY KEY (ledger_id)',
    'alter table public.digital_product_ledger add constraint digital_product_ledger_document_size_bytes_check CHECK ((document_size_bytes >= 0))',
    'alter table public.discipline_taxonomy add constraint discipline_taxonomy_pkey PRIMARY KEY (sport_code, discipline_code)',
    'alter table public.division add constraint division_pkey PRIMARY KEY (division_id)',
    'alter table public.division add constraint division_division_code_key UNIQUE (division_code)',
    'alter table public.division add constraint division_check CHECK ((age_max_years >= age_min_years))',
    'alter table public.division_scoring_rule add constraint division_scoring_rule_pkey PRIMARY KEY (rule_id)',
    'alter table public.division_scoring_rule add constraint division_scoring_rule_division_id_rule_type_rule_key_key UNIQUE (division_id, rule_type, rule_key)',
    'alter table public.division_scoring_rule add constraint division_scoring_rule_check CHECK (((((rule_type = ''sprint_grade''::text) AND (points ? ''grade_points''::text)) OR ((rule_type = ''play_style''::text) AND (points ? ''team_cohesion_points''::text) AND (points ? ''scorer_performance_points''::text)))))',
    'alter table public.division_scoring_rule add constraint division_scoring_rule_rule_type_check CHECK ((rule_type = ANY (ARRAY[''sprint_grade''::text, ''play_style''::text])))',
    'alter table public.federation add constraint federation_pkey PRIMARY KEY (federation_id)',
    'alter table public.google_form_submission_log add constraint google_form_submission_log_pkey PRIMARY KEY (submission_id)',
    'alter table public.guardian_contact add constraint guardian_contact_pkey PRIMARY KEY (guardian_id)',
    'alter table public.guardian_contact add constraint guardian_contact_relationship_check CHECK ((relationship = ANY (ARRAY[''parent''::text, ''legal_guardian''::text, ''club_appointed_guardian''::text])))',
    'alter table public.injury_record add constraint injury_record_pkey PRIMARY KEY (injury_record_id)',
    'alter table public.metric_registry add constraint metric_registry_pkey PRIMARY KEY (metric_code)',
    'alter table public.metric_registry add constraint metric_registry_data_type_check CHECK ((data_type = ANY (ARRAY[''numeric''::text, ''integer''::text, ''boolean''::text, ''text''::text])))',
    'alter table public.metric_value add constraint metric_value_pkey PRIMARY KEY (metric_value_id)',
    'alter table public.metric_value add constraint metric_value_check CHECK (((sport_profile_id IS NOT NULL) OR (performance_record_id IS NOT NULL)))',
    'alter table public.metric_value add constraint metric_value_context_check CHECK ((context = ANY (ARRAY[''in_competition''::text, ''combine_test''::text, ''training_session''::text, ''medical_exam''::text])))',
    'alter table public.performance_record add constraint performance_record_pkey PRIMARY KEY (performance_record_id)',
    'alter table public.provenance add constraint provenance_pkey PRIMARY KEY (provenance_id)',
    'alter table public.provenance add constraint provenance_confidence_score_check CHECK (((confidence_score >= (0)::numeric) AND (confidence_score <= (1)::numeric)))',
    'alter table public.representation_claim add constraint representation_claim_pkey PRIMARY KEY (claim_id)',
    'alter table public.sport_profile add constraint sport_profile_pkey PRIMARY KEY (sport_profile_id)',
    'alter table public.sport_profile add constraint sport_profile_athlete_id_sport_code_discipline_code_key UNIQUE (athlete_id, sport_code, discipline_code)',
    'alter table public.sport_profile add constraint sport_profile_dominant_side_check CHECK ((dominant_side = ANY (ARRAY[''left''::text, ''right''::text, ''ambidextrous''::text])))',
    'alter table public.sport_taxonomy add constraint sport_taxonomy_pkey PRIMARY KEY (sport_code)',
    'alter table public.transfer_event add constraint transfer_event_pkey PRIMARY KEY (transfer_id)',
    -- foreign keys last: every referenced table now exists
    'alter table athlytica_core.athletes add constraint athletes_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES athlytica_core.parents(parent_id) ON DELETE RESTRICT',
    'alter table athlytica_core.performance_logs add constraint performance_logs_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES athlytica_core.athletes(athlete_id) ON DELETE CASCADE',
    'alter table public.agent add constraint agent_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agency(agency_id)',
    'alter table public.athlete add constraint athlete_primary_sport_code_fkey FOREIGN KEY (primary_sport_code) REFERENCES public.sport_taxonomy(sport_code)',
    'alter table public.athlete add constraint athlete_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES public.provenance(provenance_id)',
    'alter table public.biometric_record add constraint biometric_record_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athlete(athlete_id) ON DELETE CASCADE',
    'alter table public.biometric_record add constraint biometric_record_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES public.provenance(provenance_id)',
    'alter table public.club add constraint club_federation_id_fkey FOREIGN KEY (federation_id) REFERENCES public.federation(federation_id)',
    'alter table public.cohort_session_registry add constraint cohort_session_registry_price_tier_id_fkey FOREIGN KEY (price_tier_id) REFERENCES public.commercial_price_tier(tier_id)',
    'alter table public.cohort_session_registry add constraint cohort_session_registry_student_athlete_id_fkey FOREIGN KEY (student_athlete_id) REFERENCES public.athlete(athlete_id)',
    'alter table public.commercial_inventory add constraint commercial_inventory_issued_to_athlete_id_fkey FOREIGN KEY (issued_to_athlete_id) REFERENCES public.athlete(athlete_id)',
    'alter table public.competition_event add constraint competition_event_sport_code_fkey FOREIGN KEY (sport_code) REFERENCES public.sport_taxonomy(sport_code)',
    'alter table public.custody_record add constraint custody_record_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athlete(athlete_id) ON DELETE CASCADE',
    'alter table public.custody_record add constraint custody_record_club_id_fkey FOREIGN KEY (club_id) REFERENCES public.club(club_id)',
    'alter table public.custody_record add constraint custody_record_federation_id_fkey FOREIGN KEY (federation_id) REFERENCES public.federation(federation_id)',
    'alter table public.custody_record add constraint custody_record_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES public.provenance(provenance_id)',
    'alter table public.custody_record add constraint custody_record_transfer_id_fkey FOREIGN KEY (transfer_id) REFERENCES public.transfer_event(transfer_id)',
    'alter table public.digital_product_ledger add constraint digital_product_ledger_licensed_to_athlete_id_fkey FOREIGN KEY (licensed_to_athlete_id) REFERENCES public.athlete(athlete_id)',
    'alter table public.discipline_taxonomy add constraint discipline_taxonomy_sport_code_fkey FOREIGN KEY (sport_code) REFERENCES public.sport_taxonomy(sport_code)',
    'alter table public.division add constraint division_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES public.provenance(provenance_id)',
    'alter table public.division add constraint division_sport_code_fkey FOREIGN KEY (sport_code) REFERENCES public.sport_taxonomy(sport_code)',
    'alter table public.division_scoring_rule add constraint division_scoring_rule_division_id_fkey FOREIGN KEY (division_id) REFERENCES public.division(division_id) ON DELETE CASCADE',
    'alter table public.division_scoring_rule add constraint division_scoring_rule_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES public.provenance(provenance_id)',
    'alter table public.division_scoring_rule add constraint division_scoring_rule_sport_code_fkey FOREIGN KEY (sport_code) REFERENCES public.sport_taxonomy(sport_code)',
    'alter table public.federation add constraint federation_sport_code_fkey FOREIGN KEY (sport_code) REFERENCES public.sport_taxonomy(sport_code)',
    'alter table public.google_form_submission_log add constraint google_form_submission_log_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athlete(athlete_id)',
    'alter table public.google_form_submission_log add constraint google_form_submission_log_registry_id_fkey FOREIGN KEY (registry_id) REFERENCES public.cohort_session_registry(registry_id)',
    'alter table public.guardian_contact add constraint guardian_contact_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athlete(athlete_id) ON DELETE CASCADE',
    'alter table public.injury_record add constraint injury_record_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athlete(athlete_id) ON DELETE CASCADE',
    'alter table public.injury_record add constraint injury_record_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES public.provenance(provenance_id)',
    'alter table public.metric_registry add constraint fk_discipline FOREIGN KEY (sport_code, discipline_code) REFERENCES public.discipline_taxonomy(sport_code, discipline_code) DEFERRABLE INITIALLY DEFERRED',
    'alter table public.metric_registry add constraint metric_registry_sport_code_fkey FOREIGN KEY (sport_code) REFERENCES public.sport_taxonomy(sport_code)',
    'alter table public.metric_value add constraint fk_metric_value_perf FOREIGN KEY (performance_record_id) REFERENCES public.performance_record(performance_record_id) ON DELETE CASCADE',
    'alter table public.metric_value add constraint metric_value_metric_code_fkey FOREIGN KEY (metric_code) REFERENCES public.metric_registry(metric_code)',
    'alter table public.metric_value add constraint metric_value_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES public.provenance(provenance_id)',
    'alter table public.metric_value add constraint metric_value_sport_profile_id_fkey FOREIGN KEY (sport_profile_id) REFERENCES public.sport_profile(sport_profile_id) ON DELETE CASCADE',
    'alter table public.performance_record add constraint performance_record_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athlete(athlete_id) ON DELETE CASCADE',
    'alter table public.performance_record add constraint performance_record_competition_event_id_fkey FOREIGN KEY (competition_event_id) REFERENCES public.competition_event(competition_event_id)',
    'alter table public.performance_record add constraint performance_record_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES public.provenance(provenance_id)',
    'alter table public.performance_record add constraint performance_record_sport_code_fkey FOREIGN KEY (sport_code) REFERENCES public.sport_taxonomy(sport_code)',
    'alter table public.representation_claim add constraint representation_claim_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES public.agency(agency_id)',
    'alter table public.representation_claim add constraint representation_claim_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agent(agent_id)',
    'alter table public.representation_claim add constraint representation_claim_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athlete(athlete_id) ON DELETE CASCADE',
    'alter table public.representation_claim add constraint representation_claim_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES public.provenance(provenance_id)',
    'alter table public.sport_profile add constraint sport_profile_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athlete(athlete_id) ON DELETE CASCADE',
    'alter table public.sport_profile add constraint sport_profile_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES public.provenance(provenance_id)',
    'alter table public.sport_profile add constraint sport_profile_sport_code_fkey FOREIGN KEY (sport_code) REFERENCES public.sport_taxonomy(sport_code)',
    'alter table public.transfer_event add constraint transfer_event_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES public.athlete(athlete_id)',
    'alter table public.transfer_event add constraint transfer_event_provenance_id_fkey FOREIGN KEY (provenance_id) REFERENCES public.provenance(provenance_id)',
    'alter table public.transfer_event add constraint transfer_event_receiving_club_id_fkey FOREIGN KEY (receiving_club_id) REFERENCES public.club(club_id)',
    'alter table public.transfer_event add constraint transfer_event_transferring_club_id_fkey FOREIGN KEY (transferring_club_id) REFERENCES public.club(club_id)'
  ]
  loop
    begin
      execute stmt;
    exception
      when duplicate_object          then null;  -- 42710: constraint of that name already present
      when duplicate_table           then null;  -- 42P07: index backing it already present
      when invalid_table_definition  then null;  -- 42P16: table already has a primary key
      when others then raise;
    end;
  end loop;
end $$;


-- ---------------------------------------------------------------------
-- 5. INDEXES (non-constraint)
-- ---------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_athlete_dob ON public.athlete USING btree (date_of_birth);
CREATE INDEX IF NOT EXISTS idx_athlete_sport ON public.athlete USING btree (primary_sport_code);
CREATE UNIQUE INDEX IF NOT EXISTS uq_athlete_passport_id ON public.athlete USING btree (passport_id) WHERE (passport_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_audit_record ON public.audit_log USING btree (record_type, record_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_biometric_athlete_date ON public.biometric_record USING btree (athlete_id, measured_at);
CREATE INDEX IF NOT EXISTS idx_cohort_session_registry_price_tier ON public.cohort_session_registry USING btree (price_tier_id);
CREATE INDEX IF NOT EXISTS idx_cohort_session_registry_student ON public.cohort_session_registry USING btree (student_athlete_id);
CREATE INDEX IF NOT EXISTS idx_cohort_session_registry_track ON public.cohort_session_registry USING btree (track_type, session_slot);
CREATE INDEX IF NOT EXISTS idx_commercial_inventory_issued_athlete ON public.commercial_inventory USING btree (issued_to_athlete_id);
CREATE INDEX IF NOT EXISTS idx_commercial_inventory_product_line ON public.commercial_inventory USING btree (product_line);
CREATE INDEX IF NOT EXISTS idx_commercial_price_tier_group ON public.commercial_price_tier USING btree (tier_group);
CREATE INDEX IF NOT EXISTS idx_custody_athlete ON public.custody_record USING btree (athlete_id, start_date);
CREATE INDEX IF NOT EXISTS idx_digital_product_ledger_licensee ON public.digital_product_ledger USING btree (licensed_to_athlete_id);
CREATE INDEX IF NOT EXISTS idx_digital_product_ledger_type ON public.digital_product_ledger USING btree (product_type);
CREATE INDEX IF NOT EXISTS idx_division_sport ON public.division USING btree (sport_code);
CREATE INDEX IF NOT EXISTS idx_division_scoring_rule_division ON public.division_scoring_rule USING btree (division_id, rule_type);
CREATE INDEX IF NOT EXISTS idx_division_scoring_rule_lookup ON public.division_scoring_rule USING btree (sport_code, rule_type, rule_key);
CREATE INDEX IF NOT EXISTS idx_injury_athlete ON public.injury_record USING btree (athlete_id, injury_date);
CREATE INDEX IF NOT EXISTS idx_metric_value_code ON public.metric_value USING btree (metric_code, measured_at);
CREATE INDEX IF NOT EXISTS idx_metric_value_profile_code ON public.metric_value USING btree (sport_profile_id, metric_code);
CREATE INDEX IF NOT EXISTS idx_perf_athlete ON public.performance_record USING btree (athlete_id);
CREATE INDEX IF NOT EXISTS idx_provenance_status ON public.provenance USING btree (verification_status);
CREATE INDEX IF NOT EXISTS idx_representation_athlete_time ON public.representation_claim USING btree (athlete_id, claimed_at);

-- D-39: uq_athlete_passport_id is redundant against athlete_passport_id_key
-- (a plain UNIQUE already permits multiple NULLs). Reproduced here because
-- production has it; drop both together or neither.


-- ---------------------------------------------------------------------
-- 6. FUNCTIONS (5)
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION athlytica_core.generate_scalable_athlete_code()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    next_sequence INT;
    padded_sequence VARCHAR(5);
BEGIN
    UPDATE athlytica_core.scalable_id_sequence
    SET current_value = current_value + 1
    WHERE id = 1
    RETURNING current_value INTO next_sequence;

    padded_sequence := LPAD(next_sequence::TEXT, 5, '0');

    NEW.ath_code := 'ATH-' || padded_sequence;

    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.generate_legacy_claim_token()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  cleaned_name TEXT;
  random_suffix TEXT;
  new_token TEXT;
  collision_check INT;
BEGIN
  IF NEW.is_legacy = TRUE AND NEW.claim_token IS NULL THEN

    cleaned_name := UPPER(REGEXP_REPLACE(SPLIT_PART(NEW.legal_name, ' ', 1), '[^a-zA-Z0-9]', '', 'g'));

    IF cleaned_name = '' OR cleaned_name IS NULL THEN
      cleaned_name := 'ATHLETE';
    END IF;

    LOOP
      random_suffix := UPPER(SUBSTRING(MD5(RANDOM()::TEXT) FROM 1 FOR 4));
      new_token := 'PLAY-' || cleaned_name || '-' || random_suffix;
      SELECT COUNT(*) INTO collision_check FROM public.athlete WHERE claim_token = new_token;
      IF collision_check = 0 THEN
        EXIT;
      END IF;
    END LOOP;

    NEW.claim_token := new_token;

  END IF;

  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.link_guardian(p_phone_e164 text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'athlytica_core', 'public'
AS $function$
declare
  v_parent_id uuid;
begin
  if p_phone_e164 !~ '^\+254[17]\d{8}$' then
    raise exception 'guardian phone must be Kenyan E.164 (+2547XXXXXXXX or +2541XXXXXXXX), got %', p_phone_e164;
  end if;

  insert into athlytica_core.parents (phone_number)
  values (p_phone_e164)
  on conflict (phone_number) do update
    set phone_number = excluded.phone_number
  returning parent_id into v_parent_id;

  return v_parent_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.trg_custody_age_band()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  dob DATE;
  age_years NUMERIC;
BEGIN
  SELECT date_of_birth INTO dob FROM athlete WHERE athlete_id = NEW.athlete_id;
  age_years := EXTRACT(YEAR FROM AGE(NEW.start_date, dob))
             + EXTRACT(MONTH FROM AGE(NEW.start_date, dob)) / 12.0;
  NEW.age_at_start_years := ROUND(age_years, 2);
  NEW.age_band := CASE
    WHEN age_years < 12 THEN 'under_12_ineligible'
    WHEN age_years >= 12 AND age_years < 16 THEN '12_15'
    WHEN age_years >= 16 AND age_years <= 23 THEN '16_23'
    ELSE 'over_23_ineligible'
  END::age_band_enum;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.onboard_athlete_from_google_form(p_form_response_id text, p_legal_name text, p_date_of_birth date, p_sex_at_birth text, p_nationalities character[], p_primary_sport_code text, p_tier_name text, p_track_type text, p_cohort_label text, p_session_slot integer, p_session_day_of_week smallint, p_window_start_time time without time zone, p_window_end_time time without time zone, p_capacity integer, p_season_start_date date, p_season_end_date date)
 RETURNS TABLE(athlete_id uuid, registry_id uuid, tier_id uuid, price_amount numeric, currency character, was_duplicate boolean)
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_existing            google_form_submission_log%ROWTYPE;
  v_athlete_id          UUID := gen_random_uuid();
  v_provenance_id       UUID;
  v_tier_id             UUID;
  v_price_amount        NUMERIC(12,2);
  v_currency            CHAR(3);
  v_registry_id         UUID;
BEGIN
  IF p_form_response_id IS NULL OR length(trim(p_form_response_id)) = 0 THEN
    RAISE EXCEPTION 'MISSING_FORM_RESPONSE_ID' USING ERRCODE = 'P0001';
  END IF;

  SELECT * INTO v_existing FROM google_form_submission_log WHERE submission_id = p_form_response_id;
  IF FOUND THEN
    SELECT cpt.tier_id, cpt.price_amount, cpt.currency
      INTO v_tier_id, v_price_amount, v_currency
    FROM cohort_session_registry csr
    JOIN commercial_price_tier cpt ON cpt.tier_id = csr.price_tier_id
    WHERE csr.registry_id = v_existing.registry_id;

    RETURN QUERY SELECT v_existing.athlete_id, v_existing.registry_id, v_tier_id, v_price_amount, v_currency, true;
    RETURN;
  END IF;

  SELECT cpt.tier_id, cpt.price_amount, cpt.currency
    INTO v_tier_id, v_price_amount, v_currency
  FROM commercial_price_tier cpt
  WHERE cpt.tier_name = p_tier_name AND cpt.is_active = true
  FOR UPDATE;

  IF v_tier_id IS NULL THEN
    RAISE EXCEPTION 'UNKNOWN_OR_INACTIVE_TIER: %', p_tier_name USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO provenance (
    data_source, entered_by_actor_id, entered_by_actor_role,
    verification_method, verification_status, source_document_hash
  ) VALUES (
    'self_reported', v_athlete_id, 'athlete',
    'none', 'unverified', encode(sha256(convert_to(p_form_response_id, 'UTF8')), 'hex')
  )
  RETURNING provenance_id INTO v_provenance_id;

  INSERT INTO athlete (
    athlete_id, legal_name, date_of_birth, sex_at_birth,
    nationalities, primary_sport_code, provenance_id
  ) VALUES (
    v_athlete_id, p_legal_name, p_date_of_birth, p_sex_at_birth,
    COALESCE(p_nationalities, '{}'), p_primary_sport_code, v_provenance_id
  );

  INSERT INTO cohort_session_registry (
    track_type, cohort_label, session_slot, session_day_of_week,
    window_start_time, window_end_time, capacity,
    season_start_date, season_end_date, student_athlete_id,
    price_tier_id, enrollment_status
  ) VALUES (
    p_track_type::training_track_type_enum, p_cohort_label, p_session_slot, p_session_day_of_week,
    p_window_start_time, p_window_end_time, p_capacity,
    p_season_start_date, p_season_end_date, v_athlete_id,
    v_tier_id, 'enrolled'
  )
  RETURNING cohort_session_registry.registry_id INTO v_registry_id;

  INSERT INTO google_form_submission_log (submission_id, athlete_id, registry_id)
  VALUES (p_form_response_id, v_athlete_id, v_registry_id);

  RETURN QUERY SELECT v_athlete_id, v_registry_id, v_tier_id, v_price_amount, v_currency, false;
END;
$function$;

-- NOTE: onboard_athlete_from_google_form is retained because it is the only
-- way to read and explain the 7 historical google_form_submission_log rows
-- (D-26c). The application route that called it was retired in 0.3H and
-- answers 410; this function has no caller.


-- ---------------------------------------------------------------------
-- 7. TRIGGERS (3)
-- ---------------------------------------------------------------------

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'custody_age_band_trigger' and not tgisinternal) then
    CREATE TRIGGER custody_age_band_trigger BEFORE INSERT OR UPDATE ON public.custody_record FOR EACH ROW EXECUTE FUNCTION public.trg_custody_age_band();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'trg_generate_claim_token' and not tgisinternal) then
    CREATE TRIGGER trg_generate_claim_token BEFORE INSERT ON public.athlete FOR EACH ROW EXECUTE FUNCTION public.generate_legacy_claim_token();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'trigger_auto_generate_scalable_ath_code' and not tgisinternal) then
    CREATE TRIGGER trigger_auto_generate_scalable_ath_code BEFORE INSERT ON athlytica_core.athletes FOR EACH ROW WHEN ((new.ath_code IS NULL)) EXECUTE FUNCTION athlytica_core.generate_scalable_athlete_code();
  end if;
end $$;


-- ---------------------------------------------------------------------
-- 8. VIEWS (3) -- all security_invoker, so the caller's RLS applies
-- ---------------------------------------------------------------------

create or replace view public.actuarial_injury_exposure_summary with (security_invoker=true) as
 SELECT a.athlete_id,
    a.primary_sport_code,
    a.date_of_birth,
    count(i.injury_record_id) AS total_injuries,
    sum(
        CASE
            WHEN i.severity = ANY (ARRAY['severe'::injury_severity_enum, 'career_threatening'::injury_severity_enum]) THEN 1
            ELSE 0
        END) AS severe_or_worse_count,
    sum(i.days_lost) AS total_days_lost,
    avg(i.training_hours_last_4wk) AS avg_recent_training_load,
    max(i.injury_date) AS most_recent_injury_date
   FROM athlete a
     LEFT JOIN injury_record i ON i.athlete_id = a.athlete_id
  GROUP BY a.athlete_id, a.primary_sport_code, a.date_of_birth;

create or replace view public.bone_age_dispute_evidence with (security_invoker=true) as
 SELECT b.athlete_id,
    a.legal_name,
    a.date_of_birth,
    b.measured_at,
    b.age_at_measurement_years,
    b.bone_age_estimate_years,
    b.bone_age_method,
    b.chronological_bone_age_delta,
    p.verification_status,
    p.verification_method
   FROM biometric_record b
     JOIN athlete a ON a.athlete_id = b.athlete_id
     JOIN provenance p ON p.provenance_id = b.provenance_id
  WHERE p.verification_status = 'verified'::verification_status
  ORDER BY b.athlete_id, b.measured_at;

create or replace view public.solidarity_claim_input with (security_invoker=true) as
 SELECT c.athlete_id,
    c.club_id,
    cl.name AS club_name,
    cl.is_training_club,
    c.age_band,
    c.start_date,
    c.end_date,
    GREATEST(0, LEAST(COALESCE(c.end_date, CURRENT_DATE), t.transfer_date) - c.start_date)::numeric / 365.25 AS years_in_band,
        CASE c.age_band
            WHEN '12_15'::age_band_enum THEN 0.0025
            WHEN '16_23'::age_band_enum THEN 0.0050
            ELSE 0::numeric
        END AS annual_rate,
    t.transfer_id,
    t.transfer_fee_amount,
    t.transfer_fee_currency,
    p.verification_status
   FROM custody_record c
     JOIN club cl ON cl.club_id = c.club_id
     JOIN transfer_event t ON t.transfer_id = c.transfer_id
     JOIN provenance p ON p.provenance_id = c.provenance_id
  WHERE c.is_training_club_flag = true AND (c.age_band = ANY (ARRAY['12_15'::age_band_enum, '16_23'::age_band_enum]));


-- ---------------------------------------------------------------------
-- 9. ROW LEVEL SECURITY -- enablement only. Policies belong to
--    20260720100000_sec001_full_surface_rls_lockdown.sql.
--    athlytica_core tables are deliberately absent: RLS is OFF there, and
--    no client role holds USAGE on the schema, which is the actual
--    containment (R2/R17). Do not add grants here.
-- ---------------------------------------------------------------------

alter table public.agency enable row level security;
alter table public.agent enable row level security;
alter table public.athlete enable row level security;
alter table public.audit_log enable row level security;
alter table public.biometric_record enable row level security;
alter table public.club enable row level security;
alter table public.cohort_session_registry enable row level security;
alter table public.commercial_inventory enable row level security;
alter table public.commercial_price_tier enable row level security;
alter table public.competition_event enable row level security;
alter table public.custody_record enable row level security;
alter table public.digital_product_ledger enable row level security;
alter table public.discipline_taxonomy enable row level security;
alter table public.division enable row level security;
alter table public.division_scoring_rule enable row level security;
alter table public.federation enable row level security;
alter table public.google_form_submission_log enable row level security;
alter table public.guardian_contact enable row level security;
alter table public.injury_record enable row level security;
alter table public.metric_registry enable row level security;
alter table public.metric_value enable row level security;
alter table public.performance_record enable row level security;
alter table public.provenance enable row level security;
alter table public.representation_claim enable row level security;
alter table public.sport_profile enable row level security;
alter table public.sport_taxonomy enable row level security;
alter table public.transfer_event enable row level security;


-- ---------------------------------------------------------------------
-- 10. GRANTS -- reproduced exactly as production holds them.
--     `anon` holds NOTHING on any of these tables, so no anon grant
--     appears below. That is deliberate and must stay true.
--     Note the breadth of the `authenticated` grants: they are wider than
--     the policies that gate them, which is D-01c's subject. Reproduced
--     faithfully rather than quietly tightened -- a baseline that improves
--     on production is not a baseline.
-- ---------------------------------------------------------------------

grant delete, insert, references, select, trigger, truncate, update on public.agency to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.agent to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.athlete to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.audit_log to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.biometric_record to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.club to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.cohort_session_registry to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.commercial_inventory to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.commercial_price_tier to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.competition_event to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.custody_record to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.digital_product_ledger to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.discipline_taxonomy to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.division to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.division_scoring_rule to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.federation to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.google_form_submission_log to service_role;
grant delete, insert, references, select, trigger, truncate, update on public.guardian_contact to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.injury_record to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.metric_registry to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.metric_value to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.performance_record to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.provenance to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.representation_claim to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.sport_profile to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.sport_taxonomy to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.transfer_event to authenticated, service_role;

grant delete, insert, references, select, trigger, truncate, update on public.actuarial_injury_exposure_summary to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.bone_age_dispute_evidence to authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.solidarity_claim_input to authenticated, service_role;

-- =====================================================================
-- END OF BASELINE
-- Next in replay order: 20260709_multi_sport_junctions.sql, whose
-- REFERENCES public.athlete(athlete_id) now resolves.
-- =====================================================================
